# Generated by Django 3.1.5 on 2021-02-04 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contasbanco', '0002_auto_20210203_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contas_bancarias',
            unique_together={('user_id', 'nome_banco')},
        ),
    ]
