# Generated by Django 3.1.5 on 2021-01-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contasbanco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=1, max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_transacao', models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Transferencia')], max_length=1)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_transacao', models.DateField()),
                ('tipo_transacao', models.CharField(choices=[('1', 'Pontual'), ('2', 'Fixa'), ('3', 'Parcelada')], default='Pontual', max_length=1)),
                ('regularidade', models.CharField(choices=[('1', 'Diário'), ('2', 'Semanal'), ('3', 'Mensal')], default='Mensal', max_length=1)),
                ('num_parcelas', models.IntegerField(default=1, max_length=5)),
                ('observacoes', models.CharField(max_length=500)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('categoria_transacao', models.OneToOneField(choices=[], on_delete=django.db.models.deletion.RESTRICT, to='transacao.categoria_transacao')),
                ('conta', models.OneToOneField(choices=[], on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('transacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transacao.transacao')),
                ('conta_destino', models.OneToOneField(choices=[], on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias')),
            ],
            bases=('transacao.transacao',),
        ),
    ]
