# Generated by Django 3.1.5 on 2021-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='num_parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
