# Generated by Django 3.1.5 on 2021-01-31 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contasbanco', '0001_initial'),
        ('transacao', '0002_auto_20210130_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria_transacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='transacao.categoria_transacao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.CharField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='regularidade',
            field=models.CharField(choices=[(1, 'Diário'), (2, 'Semanal'), (3, 'Mensal')], default='Mensal', max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[(1, 'Pontual'), (2, 'Fixa'), (3, 'Parcelada')], default='Pontual', max_length=1),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias'),
        ),
    ]
