# Generated by Django 3.1.5 on 2021-02-01 13:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0003_auto_20210131_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='regularidade',
            field=models.IntegerField(choices=[(1, 'Diário'), (2, 'Semanal'), (3, 'Mensal')], default='Mensal', max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.IntegerField(choices=[(1, 'Pontual'), (2, 'Fixa'), (3, 'Parcelada')], default='Pontual', max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
