# Generated by Django 3.1.5 on 2021-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0004_auto_20210201_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')]),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='regularidade',
            field=models.IntegerField(choices=[(1, 'Diário'), (2, 'Semanal'), (3, 'Mensal')], default='Mensal'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.IntegerField(choices=[(1, 'Pontual'), (2, 'Fixa'), (3, 'Parcelada')], default='Pontual'),
        ),
    ]
