# Generated by Django 3.1.5 on 2021-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0005_auto_20210201_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')], null=True),
        ),
    ]
