# Generated by Django 3.1.5 on 2021-02-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contasbanco', '0001_initial'),
        ('transacao', '0007_auto_20210201_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria_transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transacao.categoria_transacao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')], default=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
