# Generated by Django 3.1.5 on 2021-02-01 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacao', '0008_auto_20210201_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferencia')]),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
