# Generated by Django 3.1.5 on 2021-02-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contasbanco', '0001_initial'),
        ('transacao', '0009_auto_20210201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='conta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contasbanco.contas_bancarias'),
        ),
    ]
