# Generated by Django 3.1.5 on 2021-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0010_auto_20210202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='regularidade',
            field=models.IntegerField(choices=[(1, 'Diário'), (2, 'Semanal'), (3, 'Mensal')], default=3),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.IntegerField(choices=[(1, 'Pontual'), (2, 'Fixa'), (3, 'Parcelada')], default=1),
        ),
    ]
