# Generated by Django 3.1.5 on 2021-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0011_auto_20210202_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_transacao',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
