# Generated by Django 3.1.5 on 2021-02-04 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasbanco', '0002_auto_20210203_1529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacao', '0012_auto_20210203_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria_transacao',
            unique_together={('user_id', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('user_id', 'conta')},
        ),
    ]
