# Generated by Django 3.1.5 on 2021-02-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0013_auto_20210204_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together=set(),
        ),
    ]
