# Generated by Django 3.1.5 on 2021-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0014_auto_20210204_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=1),
        ),
    ]
