# Generated by Django 3.1.5 on 2021-02-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0022_auto_20210207_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_transacao',
            name='classe_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa'), (3, 'Transferência')], default=1),
        ),
    ]
